<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.0.0-rc17</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.17</FileVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DefineConstants>$(DefineConstants);RELEASE_DISTRIBUTION</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ChzzkOfTheLamb.Protocol\ChzzkOfTheLamb.Protocol.csproj" />
  </ItemGroup>
</Project>
